
---
Name: NSMBU Haxx
Include: ../files/include/sead
Modules:
  - aa.yaml
  - agl.yaml
  - areatask.yaml
  - ctors.yaml
  - customactors.yaml
  - distantviewmgr.yaml
  - dynamic_libs.yaml
  - profile.yaml
  - sead.yaml
  - sound.yaml
