
---
Name: NSMBU Haxx
Modules:
  - aa.yaml
  - activecollider.yaml
  - areatask.yaml
  - ctors.yaml
  - customactors.yaml
  - distantviewmgr.yaml
  - dynamic_libs.yaml
  - profile.yaml
  - sead.yaml
  - sound.yaml
